// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERROR-0]
	_ = x[EOF-1]
	_ = x[LEFT_CHEVRON-2]
	_ = x[RIGHT_CHEVRON-3]
	_ = x[SLASH-4]
	_ = x[IDENT-5]
	_ = x[ASSIGN-6]
	_ = x[QUOTE-7]
	_ = x[COLON-8]
	_ = x[ON-9]
	_ = x[TEXT-10]
	_ = x[GO_EXPRESSION-11]
	_ = x[GO_CODE-12]
	_ = x[CODE_FENCE-13]
}

const _TokenType_name = "ERROREOFLEFT_CHEVRONRIGHT_CHEVRONSLASHIDENTASSIGNQUOTECOLONONTEXTGO_EXPRESSIONGO_CODECODE_FENCE"

var _TokenType_index = [...]uint8{0, 5, 8, 20, 33, 38, 43, 49, 54, 59, 61, 65, 78, 85, 95}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
